Sortable_DLL:Sortable_DLL_Driver.o Sortable_DLL_Implementation.o
	gcc -o Sortable_DLL Sortable_DLL_Driver.o Sortable_DLL_Implementation.o
Sortable_DLL_Driver.o:Sortable_DLL_Driver.c Sortable_DLL.h
	gcc -c Sortable_DLL_Driver.c
Sortable_DLL_Implementation.o:Sortable_DLL_Implementation.c Sortable_DLL.h
	gcc -c Sortable_DLL_Implementation.c
