Assg9:Assg9_Driver.o Assg9_Implementation.o
	gcc -o Assg9 Assg9_Driver.o Assg9_Implementation.o
Assg9_Driver.o:Assg9_Driver.c Assg9.h
	gcc -c Assg9_Driver.c
Assg9_Implementation.o:Assg9_Implementation.c Assg9.h
	gcc -c Assg9_Implementation.c
