Assg8:Assg8_Driver.o Assg8_Implementation.o
	gcc -o Assg8 Assg8_Driver.o Assg8_Implementation.o
Assg8_Driver.o:Assg8_Driver.c Assg8.h
	gcc -c Assg8_Driver.c
Assg8_Implementation.o:Assg8_Implementation.c Assg8.h
	gcc -c Assg8_Implementation.c

