Assg7:Assg7_Driver.o Assg7_Implementation.o
	gcc -o Assg7 Assg7_Driver.o Assg7_Implementation.o -lm
Assg7_Driver.o:Assg7_Driver.c Assg7.h
	gcc -c Assg7_Driver.c
Assg7_Implementation.o:Assg7_Implementation.c Assg7.h
	gcc -c Assg7_Implementation.c
